// Module C+D — thuốc & hóa chất gia dụng + vật sắc (dao kéo)
// Thử nghiệm phụ Bé Gấu An Toàn. Chưa chuyên gia duyệt. Không thu PII.
// Ranh giới: không nếm / không tự gây nôn; báo người lớn; dao kéo chỉ với người lớn; không hù dọa.

export const LESSONS = [
  // ——— Module C: khac-thuoc ———
  {
    id: 'khac-thuoc-l1',
    moduleId: 'khac-thuoc',
    gradeBand: '1-2',
    title: 'Không phải nước ngọt',
    objective: 'Nhận chai tẩy / nước rửa có thể trông giống đồ uống → không uống; hỏi người lớn.',
    teacherPrompt: 'Cùng trẻ nhìn nhãn và màu chai (mô tả nhẹ). Nhắc: chỉ uống đồ người lớn đưa và nói rõ là đồ uống.',
    situations: [
      {
        id: 'khac-thuoc-l1-s1',
        hazard: 'chai trong suốt trên bàn bếp',
        prompt: 'Bé Gấu thấy một chai trong suốt trên bàn bếp, nước màu vàng nhạt. Em khát. Người lớn đang ở phòng bên. Bé Gấu làm gì?',
        safeText: 'Không uống. Gọi người lớn hỏi đó có phải đồ uống không.',
        safeFeedback: 'Giỏi! Bé Gấu không tự uống và hỏi người lớn trước.',
        unsafeChoices: [
          { text: 'Uống một ngụm vì trông giống nước ngọt.', feedback: 'Chai trong nhà bếp chưa chắc là đồ uống. Hỏi người lớn trước nhé.' },
          { text: 'Ngửi rồi uống nếu thơm.', feedback: 'Không ngửi thử rồi uống. Chỉ hỏi người lớn.' },
        ],
      },
      {
        id: 'khac-thuoc-l1-s2',
        hazard: 'chai nước rửa cạnh ly nước',
        prompt: 'Trên bồn rửa có một ly nước và một chai nước rửa chén. Bé Gấu muốn uống nước. Em làm gì?',
        safeText: 'Chỉ uống từ ly người lớn đưa; không đụng chai nước rửa.',
        safeFeedback: 'Đúng rồi! Uống đúng ly, không lẫn với chai rửa chén.',
        unsafeChoices: [
          { text: 'Uống từ chai nào gần hơn.', feedback: 'Không uống từ chai lạ. Chỉ dùng ly người lớn đưa.' },
          { text: 'Đổ chai rửa vào ly cho giống nước.', feedback: 'Không đổ lẫn. Gọi người lớn nếu chưa rõ ly nào.' },
        ],
      },
      {
        id: 'khac-thuoc-l1-s3',
        hazard: 'chai không nhãn trong tủ dưới bếp',
        prompt: 'Bé Gấu mở tủ dưới bếp chơi và thấy một chai không có nhãn. Em tò mò. Bé Gấu làm gì?',
        safeText: 'Đóng tủ lại, không mở nắp, gọi người lớn đến xem.',
        safeFeedback: 'Tốt! Chai không nhãn thì nhờ người lớn, không tự mở.',
        unsafeChoices: [
          { text: 'Mở nắp xem bên trong có gì.', feedback: 'Không mở nắp chai lạ. Gọi người lớn giúp.' },
          { text: 'Chạm ngón tay vào chất trong chai.', feedback: 'Không chạm thử. Đóng tủ và báo người lớn.' },
        ],
      },
      {
        id: 'khac-thuoc-l1-s4',
        hazard: 'bạn bảo “thử một chút”',
        prompt: 'Bạn bảo Bé Gấu: “Thử một chút nước trong chai tẩy xem có ngọt không.” Người lớn ở gần. Bé Gấu làm gì?',
        safeText: 'Nói không; đứng xa chai cùng bạn; gọi người lớn.',
        safeFeedback: 'Hay lắm! Bé Gấu không thử, không kéo bạn sát chai, và nhờ người lớn.',
        unsafeChoices: [
          { text: 'Thử một giọt cho vui.', feedback: 'Không thử dù chỉ một giọt. Báo người lớn ngay.' },
          { text: 'Cười và nhìn bạn thử.', feedback: 'Nhắc bạn dừng và gọi người lớn, không đứng xem thử.' },
        ],
      },
      {
        id: 'khac-thuoc-l1-s5',
        hazard: 'chai đẹp trên kệ thấp',
        prompt: 'Trên kệ thấp có chai màu hồng đẹp, nắp dễ mở. Bé Gấu muốn cầm chơi. Em làm gì?',
        safeText: 'Không cầm chai đó. Nhờ người lớn cất lên cao hoặc khóa tủ.',
        safeFeedback: 'Đúng! Chai hóa chất không phải đồ chơi; nhờ người lớn cất.',
        unsafeChoices: [
          { text: 'Cầm chai lắc xem có kêu không.', feedback: 'Không lắc chai lạ. Gọi người lớn cất giúp.' },
          { text: 'Mang chai ra sân chơi với bạn.', feedback: 'Chai đó không đem đi chơi. Báo người lớn.' },
        ],
      },
    ],
  },
  {
    id: 'khac-thuoc-l2',
    moduleId: 'khac-thuoc',
    gradeBand: '1-3',
    title: 'Tủ thuốc của người lớn',
    objective: 'Không tự mở / lấy thuốc; thuốc chỉ người lớn đưa đúng lúc.',
    teacherPrompt: 'Nhắc: tủ thuốc là chỗ của người lớn. Trẻ không tự lấy dù “biết đường”.',
    situations: [
      {
        id: 'khac-thuoc-l2-s1',
        hazard: 'tủ thuốc mở sẵn',
        prompt: 'Tủ thuốc đang hé mở. Bé Gấu thấy vài hộp thuốc. Em hơi đau đầu. Bé Gấu làm gì?',
        safeText: 'Không lấy thuốc. Gọi người lớn nói mình đau đầu.',
        safeFeedback: 'Giỏi! Người lớn mới quyết định có cần thuốc không.',
        unsafeChoices: [
          { text: 'Tự lấy một viên vì đã thấy bố mẹ uống.', feedback: 'Không tự lấy thuốc. Báo người lớn trước.' },
          { text: 'Đóng tủ rồi tự tìm thuốc ở túi xách.', feedback: 'Không tìm thuốc một mình. Gọi người lớn giúp.' },
        ],
      },
      {
        id: 'khac-thuoc-l2-s2',
        hazard: 'thuốc để trên bàn ngủ',
        prompt: 'Trên bàn ngủ có vỉ thuốc của ông bà. Bé Gấu muốn “giúp” xếp lại cho gọn. Em làm gì?',
        safeText: 'Không đụng vỉ thuốc. Gọi người lớn xếp hoặc cất.',
        safeFeedback: 'Tốt! Thuốc do người lớn cất, Bé Gấu không tự xếp.',
        unsafeChoices: [
          { text: 'Bóc vài viên ra cho đẹp hộp.', feedback: 'Không bóc thuốc. Nhờ người lớn xử lý.' },
          { text: 'Cất thuốc vào hộp đồ chơi của mình.', feedback: 'Không đem thuốc vào đồ chơi. Gọi người lớn.' },
        ],
      },
      {
        id: 'khac-thuoc-l2-s3',
        hazard: 'em bé khóc, muốn “cho thuốc”',
        prompt: 'Em bé khóc. Bé Gấu nhớ nhà có siro ho. Người lớn đang nấu cơm. Bé Gấu làm gì?',
        safeText: 'Gọi người lớn đến xem em bé; không tự lấy hay đổ siro.',
        safeFeedback: 'Đúng! Chỉ người lớn mới cho thuốc khi cần.',
        unsafeChoices: [
          { text: 'Đổ một ít siro vào miệng em bé.', feedback: 'Không tự cho thuốc. Gọi người lớn ngay.' },
          { text: 'Mở chai siro sẵn để người lớn khỏi mất công.', feedback: 'Không mở chai thuốc. Để người lớn tự lấy.' },
        ],
      },
      {
        id: 'khac-thuoc-l2-s4',
        hazard: 'chìa khóa tủ thuốc',
        prompt: 'Bé Gấu thấy chìa khóa tủ thuốc để trên bàn. Em biết tủ đó. Bé Gấu làm gì?',
        safeText: 'Không mở tủ. Đưa chìa cho người lớn hoặc báo họ cất.',
        safeFeedback: 'Hay! Bé Gấu trả chìa cho người lớn, không tự mở tủ thuốc.',
        unsafeChoices: [
          { text: 'Mở tủ xem có kẹo vitamin không.', feedback: 'Không mở tủ thuốc. Đưa chìa cho người lớn.' },
          { text: 'Giấu chìa để “bảo vệ” tủ.', feedback: 'Không giấu chìa. Đưa lại người lớn.' },
        ],
      },
      {
        id: 'khac-thuoc-l2-s5',
        hazard: 'bạn bảo lấy thuốc giảm đau',
        prompt: 'Bạn đau bụng, bảo Bé Gấu vào tủ thuốc nhà Bé Gấu lấy viên giảm đau. Người lớn ở ngoài sân. Bé Gấu làm gì?',
        safeText: 'Không lấy thuốc. Cùng bạn gọi người lớn của nhà mình.',
        safeFeedback: 'Giỏi! Thuốc không tự phát; người lớn sẽ giúp.',
        unsafeChoices: [
          { text: 'Lấy một viên đưa bạn cho đỡ đau.', feedback: 'Không đưa thuốc cho bạn. Gọi người lớn.' },
          { text: 'Cho bạn tự vào tủ lấy.', feedback: 'Không để bạn vào tủ thuốc. Gọi người lớn giúp.' },
        ],
      },
    ],
  },
  {
    id: 'khac-thuoc-l3',
    moduleId: 'khac-thuoc',
    gradeBand: '2-4',
    title: 'Giống kẹo nhưng là thuốc',
    objective: 'Không ăn viên thuốc vì “giống kẹo”; báo người lớn.',
    teacherPrompt: 'Nhấn: màu sắc / hình viên không đủ để biết là kẹo. Chỉ ăn đồ người lớn nói rõ là đồ ăn.',
    situations: [
      {
        id: 'khac-thuoc-l3-s1',
        hazard: 'viên thuốc màu hồng trên bàn',
        prompt: 'Trên bàn có viên nhỏ màu hồng, trông giống kẹo. Không ai nói đó là gì. Bé Gấu làm gì?',
        safeText: 'Không bỏ vào miệng. Gọi người lớn hỏi và nhờ cất.',
        safeFeedback: 'Đúng! Trông giống kẹo chưa chắc là kẹo — hỏi người lớn.',
        unsafeChoices: [
          { text: 'Nếm một chút xem có ngọt không.', feedback: 'Không nếm thử. Báo người lớn ngay.' },
          { text: 'Ăn hết vì màu đẹp.', feedback: 'Không ăn viên lạ. Gọi người lớn giúp.' },
        ],
      },
      {
        id: 'khac-thuoc-l3-s2',
        hazard: 'kẹo vitamin của người lớn',
        prompt: 'Ông đưa Bé Gấu xem hộp “kẹo vitamin” của ông, rồi để trên bàn và ra ngoài. Bé Gấu muốn ăn thêm. Em làm gì?',
        safeText: 'Không tự lấy. Đợi ông về hoặc gọi người lớn khác hỏi.',
        safeFeedback: 'Tốt! Dù gọi là kẹo vitamin cũng chỉ dùng khi người lớn đưa.',
        unsafeChoices: [
          { text: 'Lấy hai viên vì ông hay cho mình.', feedback: 'Không tự lấy. Chờ người lớn đưa đúng số.' },
          { text: 'Chia viên cho bạn đang chơi cùng.', feedback: 'Không chia thuốc/vitamin. Nhờ người lớn quyết định.' },
        ],
      },
      {
        id: 'khac-thuoc-l3-s3',
        hazard: 'vỏ vỉ thuốc trống và viên rơi',
        prompt: 'Bé Gấu thấy một viên thuốc rơi dưới ghế và vỏ vỉ gần đó. Em làm gì?',
        safeText: 'Không nhặt bỏ miệng. Gọi người lớn nhặt và cất.',
        safeFeedback: 'Giỏi! Viên rơi dưới đất không phải kẹo — nhờ người lớn.',
        unsafeChoices: [
          { text: 'Nhặt lên thổi rồi ăn.', feedback: 'Không ăn viên nhặt được. Báo người lớn.' },
          { text: 'Bỏ viên vào túi để “giữ làm kỷ niệm”.', feedback: 'Không giữ thuốc trong túi. Đưa người lớn cất.' },
        ],
      },
      {
        id: 'khac-thuoc-l3-s4',
        hazard: 'bạn khoe “kẹo nhà mình”',
        prompt: 'Bạn lấy từ túi vài viên tròn, bảo là kẹo nhà đem, mời Bé Gấu ăn. Bé Gấu chưa thấy người lớn nào đưa. Em làm gì?',
        safeText: 'Từ chối lịch sự, nhờ bạn hỏi người lớn trước khi ăn.',
        safeFeedback: 'Hay! Bé Gấu không ăn đồ chưa rõ và nhắc bạn hỏi người lớn.',
        unsafeChoices: [
          { text: 'Ăn một viên cho vui với bạn.', feedback: 'Không ăn khi chưa rõ. Nhờ người lớn kiểm tra.' },
          { text: 'Đòi thêm rồi để dành ăn sau.', feedback: 'Không nhận viên lạ. Báo người lớn gần nhất.' },
        ],
      },
      {
        id: 'khac-thuoc-l3-s5',
        hazard: 'nhầm hộp kẹo và hộp thuốc',
        prompt: 'Hai hộp giống nhau: một hộp kẹo, một hộp thuốc. Bé Gấu không chắc hộp nào. Em muốn ăn kẹo. Bé Gấu làm gì?',
        safeText: 'Không mở hộp một mình. Đưa cả hai cho người lớn chọn hộp kẹo.',
        safeFeedback: 'Đúng! Người lớn đọc nhãn giúp trước khi Bé Gấu ăn.',
        unsafeChoices: [
          { text: 'Mở cả hai hộp nếm xem hộp nào ngọt.', feedback: 'Không nếm để phân biệt. Nhờ người lớn đọc nhãn.' },
          { text: 'Chọn hộp màu đẹp hơn rồi ăn.', feedback: 'Màu hộp không đủ. Hỏi người lớn trước.' },
        ],
      },
    ],
  },
  {
    id: 'khac-thuoc-l4',
    moduleId: 'khac-thuoc',
    gradeBand: '3-5',
    title: 'Thấy bạn định nếm',
    objective: 'Khuyên dừng + gọi người lớn; không đùa “thử xem”.',
    teacherPrompt: 'Luyện câu ngắn: “Đừng nếm, mình gọi chú/cô/bố mẹ.” Không biến thành trò dọa.',
    situations: [
      {
        id: 'khac-thuoc-l4-s1',
        hazard: 'bạn sắp uống nước lau sàn',
        prompt: 'Bạn cầm chai nước lau sàn, định uống vì chai trong suốt. Bé Gấu làm gì?',
        safeText: 'Nhắc bạn dừng ngay, không uống; không cầm chai; gọi người lớn đến cất chai.',
        safeFeedback: 'Giỏi! Bé Gấu nhắc dừng và gọi người lớn; trẻ không tự cầm hóa chất.',
        unsafeChoices: [
          { text: 'Cười bảo “thử một ngụm đi”.', feedback: 'Không đùa thử. Nhắc dừng và gọi người lớn.' },
          { text: 'Quay đi vì “không phải việc của mình”.', feedback: 'Bạn cần giúp: nhắc dừng và gọi người lớn.' },
        ],
      },
      {
        id: 'khac-thuoc-l4-s2',
        hazard: 'thách nếm thuốc',
        prompt: 'Trong giờ chơi, một bạn thách: ai dám bỏ viên thuốc vào miệng. Bé Gấu làm gì?',
        safeText: 'Nói không tham gia, nhắc mọi người dừng, tìm người lớn gần nhất.',
        safeFeedback: 'Đúng! Trò thách nếm thuốc không chơi; gọi người lớn.',
        unsafeChoices: [
          { text: 'Nhận thách cho “ngầu”.', feedback: 'Không nhận thách nguy hiểm. Báo người lớn.' },
          { text: 'Quay video bạn nếm rồi mới gọi người lớn.', feedback: 'Dừng ngay và gọi người lớn trước, không quay để đùa.' },
        ],
      },
      {
        id: 'khac-thuoc-l4-s3',
        hazard: 'bạn mở chai tẩy trong nhà vệ sinh',
        prompt: 'Bạn mở chai tẩy trong nhà vệ sinh, định ngửi xem “mạnh không”. Bé Gấu ở cạnh. Em làm gì?',
        safeText: 'Nhắc đóng nắp, không ngửi, cùng ra ngoài gọi người lớn.',
        safeFeedback: 'Tốt! Không ngửi thử hóa chất — báo người lớn cất giúp.',
        unsafeChoices: [
          { text: 'Cũng ngửi một cái cho biết.', feedback: 'Không ngửi thử. Nhắc đóng nắp và gọi người lớn.' },
          { text: 'Đổ ít ra sàn xem có bọt không.', feedback: 'Không đổ thử. Gọi người lớn xử lý chai.' },
        ],
      },
      {
        id: 'khac-thuoc-l4-s4',
        hazard: 'em nhỏ với ống kem đánh răng lớn',
        prompt: 'Em nhỏ nhà bạn định “ăn” kem đánh răng vì tưởng kem ngọt. Bé Gấu làm gì?',
        safeText: 'Nhắc em không đưa vào miệng; gọi ngay người lớn của nhà bạn.',
        safeFeedback: 'Hay! Bé Gấu báo người lớn ngay, không tự xử lý ống kem thay họ.',
        unsafeChoices: [
          { text: 'Bôi kem lên lưỡi em cho vui.', feedback: 'Không cho em nếm. Gọi người lớn ngay.' },
          { text: 'Bảo em nuốt để hết sâu răng.', feedback: 'Không bảo nuốt. Gọi người lớn ngay.' },
        ],
      },
      {
        id: 'khac-thuoc-l4-s5',
        hazard: 'bạn giấu chai hóa chất trong cặp',
        prompt: 'Bạn khoe đã bỏ chai nước rửa nhỏ vào cặp “mang đi chơi”. Bé Gấu làm gì?',
        safeText: 'Khuyên không mang hóa chất đi chơi; cùng báo người lớn để họ lấy chai ra và cất.',
        safeFeedback: 'Đúng! Hóa chất không mang đi chơi — để người lớn lấy và cất.',
        unsafeChoices: [
          { text: 'Xin chia chai để mang về nhà mình.', feedback: 'Không chia hóa chất. Báo người lớn cất.' },
          { text: 'Giữ bí mật giúp bạn.', feedback: 'Không giữ bí mật nguy hiểm. Báo người lớn giúp cất.' },
        ],
      },
    ],
  },
  {
    id: 'khac-thuoc-l5',
    moduleId: 'khac-thuoc',
    gradeBand: '3-5',
    title: 'Khi nghi ngờ uống nhầm',
    objective: 'Không tự gây nôn / mẹo dân gian; lập tức tìm người lớn tin cậy để họ quyết định gọi 115 / đưa cơ sở y tế.',
    teacherPrompt: 'Chỉ dạy: báo người lớn ngay. Không hướng dẫn gây nôn, không liệt kê triệu chứng nặng gây sợ.',
    situations: [
      {
        id: 'khac-thuoc-l5-s1',
        hazard: 'nghi mình uống nhầm',
        prompt: 'Bé Gấu vừa uống nhầm một ngụm từ chai lạ trên bàn. Em hơi lo. Người lớn ở phòng khách. Bé Gấu làm gì?',
        safeText: 'Đến ngay người lớn, nói rõ vừa uống từ chai nào; để họ quyết định bước tiếp.',
        safeFeedback: 'Giỏi! Báo người lớn ngay là việc đúng nhất.',
        unsafeChoices: [
          { text: 'Tự gây nôn cho “sạch bụng”.', feedback: 'Không tự gây nôn. Tìm người lớn ngay để họ xử lý.' },
          { text: 'Im lặng uống nước lọc thật nhiều rồi chờ.', feedback: 'Không tự xử lý một mình. Báo người lớn liền.' },
        ],
      },
      {
        id: 'khac-thuoc-l5-s2',
        hazard: 'bạn nói đã nuốt viên thuốc lạ',
        prompt: 'Bạn thì thầm vừa nuốt một viên nhặt được dưới sàn. Bé Gấu làm gì?',
        safeText: 'Đưa bạn đến người lớn tin cậy, nói ngắn: bạn vừa nuốt viên nhặt được.',
        safeFeedback: 'Đúng! Người lớn sẽ quyết định có cần gọi 115 hay đưa đi khám.',
        unsafeChoices: [
          { text: 'Bảo bạn thọc tay vào miệng cho ói ra.', feedback: 'Không bảo bạn gây nôn. Gọi người lớn ngay.' },
          { text: 'Hứa giữ bí mật nếu bạn không sao.', feedback: 'Không giữ bí mật. Báo người lớn giúp bạn.' },
        ],
      },
      {
        id: 'khac-thuoc-l5-s3',
        hazard: 'nghe mẹo dân gian trên mạng',
        prompt: 'Ai đó nói trên điện thoại: uống nhầm hóa chất thì uống dầu ăn cho “đẩy ra”. Bé Gấu nghi em mình vừa chạm miệng vào chai. Em làm gì?',
        safeText: 'Không làm theo Mẹ Gấuo. Gọi người lớn thật trong nhà ngay.',
        safeFeedback: 'Tốt! Không theo Mẹ Gấuo dân gian — người lớn quyết định đúng cách.',
        unsafeChoices: [
          { text: 'Đổ dầu ăn cho em uống theo clip.', feedback: 'Không tự chữa theo Mẹ Gấuo. Báo người lớn liền.' },
          { text: 'Pha nước muối bảo em súc rồi nuốt.', feedback: 'Không tự pha hay bắt nuốt. Tìm người lớn.' },
        ],
      },
      {
        id: 'khac-thuoc-l5-s4',
        hazard: 'chai nghi ngờ và số 115',
        prompt: 'Người lớn đang bận nghe điện thoại dài. Bé Gấu sợ em bé vừa uống nhầm. Em làm gì?',
        safeText: 'Lại gần người lớn, nói rõ và gấp: “Em bé có thể đã uống nhầm.” Để người lớn gọi 115 nếu cần.',
        safeFeedback: 'Hay! Bé Gấu báo rõ và để người lớn gọi cấp cứu khi cần.',
        unsafeChoices: [
          { text: 'Tự gọi 115 rồi tắt máy vì ngại nói.', feedback: 'Gọi người lớn trước; họ sẽ nói với tổng đài nếu cần.' },
          { text: 'Tự tìm cách gây nôn cho em bé.', feedback: 'Không gây nôn. Báo người lớn ngay.' },
        ],
      },
      {
        id: 'khac-thuoc-l5-s5',
        hazard: 'sau khi đã báo người lớn',
        prompt: 'Bé Gấu đã báo người lớn về việc nghi uống nhầm. Người lớn đang gọi điện. Em còn lại chai trên bàn. Bé Gấu làm gì?',
        safeText: 'Không đụng chai thêm; đứng gần nơi người lớn bảo chờ, trả lời họ hỏi gì đã xảy ra.',
        safeFeedback: 'Đúng! Giữ khoảng cách với chai và hỗ trợ người lớn bằng lời nói thật.',
        unsafeChoices: [
          { text: 'Rửa chai thật sạch để “xóa dấu”.', feedback: 'Không rửa hay giấu chai; người lớn có thể cần xem.' },
          { text: 'Tự chạy ra đường tìm phòng khám một mình.', feedback: 'Ở với người lớn; không tự đi một mình.' },
        ],
      },
    ],
  },

  // ——— Module D: khac-sac ———
  {
    id: 'khac-sac-l1',
    moduleId: 'khac-sac',
    gradeBand: '1-2',
    title: 'Tay không chạm',
    objective: 'Nhận dao / kéo lớn trên bàn bếp → không cầm; gọi người lớn.',
    teacherPrompt: 'Chỉ nhận biết và báo. Không mô tả vết thương.',
    situations: [
      {
        id: 'khac-sac-l1-s1',
        hazard: 'dao trên bàn bếp',
        prompt: 'Trên bàn bếp có con dao để gần mép bàn. Bé Gấu muốn lấy đĩa bên cạnh. Em làm gì?',
        safeText: 'Không cầm dao. Gọi người lớn cất dao rồi mới lấy đĩa giúp hoặc nhờ họ lấy.',
        safeFeedback: 'Giỏi! Dao để người lớn cất; Bé Gấu không chạm.',
        unsafeChoices: [
          { text: 'Cầm dao gạt sang một bên rồi lấy đĩa.', feedback: 'Không cầm dao. Gọi người lớn giúp.' },
          { text: 'Đẩy dao bằng khuỷu tay cho khỏi vướng.', feedback: 'Không tự đẩy dao. Báo người lớn.' },
        ],
      },
      {
        id: 'khac-sac-l1-s2',
        hazard: 'kéo lớn trong ngăn kéo mở',
        prompt: 'Ngăn kéo bếp đang mở, có kéo lớn. Bé Gấu tò mò. Em làm gì?',
        safeText: 'Không lấy kéo. Đóng ngăn nếu an toàn hoặc gọi người lớn đóng và cất.',
        safeFeedback: 'Tốt! Kéo lớn không phải đồ chơi — nhờ người lớn.',
        unsafeChoices: [
          { text: 'Cầm kéo ra xem lưỡi có sáng không.', feedback: 'Không cầm kéo lớn. Gọi người lớn.' },
          { text: 'Đưa kéo cho em nhỏ hơn chơi.', feedback: 'Không đưa kéo cho em. Báo người lớn cất.' },
        ],
      },
      {
        id: 'khac-sac-l1-s3',
        hazard: 'dao ở giá thấp',
        prompt: 'Giá để dao ở tầm tay Bé Gấu. Em muốn “giúp xếp bếp”. Bé Gấu làm gì?',
        safeText: 'Không rút dao. Nhờ người lớn xếp hoặc để việc khác không sắc.',
        safeFeedback: 'Đúng! Việc có dao để người lớn làm.',
        unsafeChoices: [
          { text: 'Rút dao ra lau cho sạch.', feedback: 'Không rút dao. Gọi người lớn nếu cần lau.' },
          { text: 'Đếm số dao bằng cách cầm từng con.', feedback: 'Không cầm từng dao. Nhờ người lớn.' },
        ],
      },
      {
        id: 'khac-sac-l1-s4',
        hazard: 'bạn với dao đồ chơi kim loại',
        prompt: 'Bạn mang “dao đồ chơi” bằng kim loại sắc từ nhà bếp ra phòng khách. Bé Gấu làm gì?',
        safeText: 'Nhắc bạn để xuống, cùng gọi người lớn cất đồ sắc.',
        safeFeedback: 'Hay! Đồ sắc không đem ra chơi — báo người lớn.',
        unsafeChoices: [
          { text: 'Xin cầm thử một lúc.', feedback: 'Không cầm thử. Gọi người lớn cất giúp.' },
          { text: 'Đùa chém gió với bạn bằng dao đó.', feedback: 'Không đùa với dao. Nhắc dừng và gọi người lớn.' },
        ],
      },
      {
        id: 'khac-sac-l1-s5',
        hazard: 'thớt và dao vừa dùng xong',
        prompt: 'Người lớn vừa cắt xong, bước sang phòng khác trong giây lát. Dao còn trên thớt. Bé Gấu muốn ăn miếng trái cây đã cắt. Em làm gì?',
        safeText: 'Không lấy gần dao. Gọi người lớn lấy trái cây hoặc cất dao trước.',
        safeFeedback: 'Giỏi! Chờ người lớn; không với tay gần dao.',
        unsafeChoices: [
          { text: 'Tự gạt dao sang rồi lấy trái cây.', feedback: 'Không gạt dao. Gọi người lớn giúp.' },
          { text: 'Cầm dao chặt thêm miếng cho to.', feedback: 'Không cầm dao cắt. Nhờ người lớn.' },
        ],
      },
    ],
  },
  {
    id: 'khac-sac-l2',
    moduleId: 'khac-sac',
    gradeBand: '2-3',
    title: 'Kéo học tập',
    objective: 'Chỉ dùng kéo được giao ở bàn học; cầm đúng cách theo hướng dẫn người lớn; không chạy khi cầm kéo.',
    teacherPrompt: 'Ôn tư thế ngồi, hướng lưỡi kéo, trả kéo khi xong. Luôn có người lớn giám sát.',
    situations: [
      {
        id: 'khac-sac-l2-s1',
        hazard: 'kéo thủ công trên bàn học',
        prompt: 'Cô / người lớn giao kéo thủ công và giấy. Bé Gấu muốn cắt. Em làm gì?',
        safeText: 'Ngồi tại bàn, cầm kéo như người lớn chỉ, cắt chậm, không đưa kéo về phía bạn.',
        safeFeedback: 'Đúng! Cắt tại bàn theo hướng dẫn người lớn.',
        unsafeChoices: [
          { text: 'Đứng dậy vừa đi vừa cắt cho nhanh.', feedback: 'Không đi khi cầm kéo. Ngồi cắt tại bàn.' },
          { text: 'Quay lưỡi kéo về phía bạn bên cạnh.', feedback: 'Không hướng kéo về người khác. Nhờ người lớn nhắc cách cầm.' },
        ],
      },
      {
        id: 'khac-sac-l2-s2',
        hazard: 'chạy cầm kéo',
        prompt: 'Bạn gọi Bé Gấu sang bàn khác. Tay Bé Gấu đang cầm kéo. Em làm gì?',
        safeText: 'Để kéo xuống bàn hoặc đóng lưỡi kéo rồi đi; không chạy khi cầm kéo.',
        safeFeedback: 'Tốt! Đặt kéo xuống rồi mới đi gặp bạn.',
        unsafeChoices: [
          { text: 'Chạy sang cầm kéo trên tay.', feedback: 'Không chạy cầm kéo. Để kéo xuống trước.' },
          { text: 'Ném kéo nhẹ sang bàn bạn.', feedback: 'Không ném kéo. Đi bộ và nhờ người lớn nếu cần chuyển.' },
        ],
      },
      {
        id: 'khac-sac-l2-s3',
        hazard: 'kéo không được giao',
        prompt: 'Trên tủ giáo viên / tủ nhà có kéo lớn hơn kéo thủ công. Bé Gấu muốn cắt hộp cứng. Em làm gì?',
        safeText: 'Không tự lấy kéo lớn. Nhờ người lớn cắt hộp hoặc chọn dụng cụ phù hợp.',
        safeFeedback: 'Giỏi! Chỉ dùng kéo được giao; hộp cứng nhờ người lớn.',
        unsafeChoices: [
          { text: 'Tự lấy kéo lớn trên tủ.', feedback: 'Không tự lấy kéo lớn. Gọi người lớn giúp.' },
          { text: 'Dùng kéo thủ công cố cắt thật mạnh một mình.', feedback: 'Nếu khó cắt, dừng và nhờ người lớn, không cố hết sức.' },
        ],
      },
      {
        id: 'khac-sac-l2-s4',
        hazard: 'trả kéo khi xong',
        prompt: 'Bé Gấu cắt xong. Người lớn đang giúp bạn khác. Em làm gì với kéo?',
        safeText: 'Đóng kéo, để đúng chỗ người lớn chỉ, hoặc đưa lại khi họ rảnh.',
        safeFeedback: 'Đúng! Trả / để kéo đúng chỗ, không để lung tung.',
        unsafeChoices: [
          { text: 'Bỏ kéo vào túi áo mang đi chơi.', feedback: 'Không bỏ kéo vào túi. Để đúng chỗ người lớn chỉ.' },
          { text: 'Cắm kéo đứng trên ghế cho “gọn”.', feedback: 'Không cắm kéo lên ghế. Để nằm đúng khay / chỗ quy định.' },
        ],
      },
      {
        id: 'khac-sac-l2-s5',
        hazard: 'tranh giành kéo',
        prompt: 'Hai bạn tranh một cây kéo. Bé Gấu ở gần. Em làm gì?',
        safeText: 'Nhắc không giật kéo, gọi người lớn chia lượt hoặc thêm kéo.',
        safeFeedback: 'Hay! Không giật kéo — nhờ người lớn giải quyết.',
        unsafeChoices: [
          { text: 'Giật kéo giúp bạn mình.', feedback: 'Không giật kéo. Gọi người lớn giúp.' },
          { text: 'Cầm kéo chỉ về phía hai bạn để “dọa dừng”.', feedback: 'Không dùng kéo để dọa. Gọi người lớn.' },
        ],
      },
    ],
  },
  {
    id: 'khac-sac-l3',
    moduleId: 'khac-sac',
    gradeBand: '2-4',
    title: 'Giúp bếp cùng người lớn',
    objective: '“Giúp” chỉ việc không sắc (rửa rau đã cắt sẵn…); không tự cắt khi người lớn không đứng cạnh.',
    teacherPrompt: 'Liệt kê việc trẻ được làm vs việc chỉ người lớn. Luôn có người lớn đứng cạnh nếu có dụng cụ sắc.',
    situations: [
      {
        id: 'khac-sac-l3-s1',
        hazard: 'muốn cắt rau giúp',
        prompt: 'Bé Gấu muốn giúp nấu. Trên thớt có dao và rau chưa cắt. Người lớn đang rửa tay cách đó vài bước. Em làm gì?',
        safeText: 'Chờ người lớn đứng cạnh và giao việc; không tự cầm dao cắt.',
        safeFeedback: 'Đúng! Chỉ cắt khi người lớn giao và đứng cạnh.',
        unsafeChoices: [
          { text: 'Tự cắt vài nhát cho nhanh trước khi họ về.', feedback: 'Không tự cắt. Chờ người lớn bên cạnh.' },
          { text: 'Cầm dao “làm sẵn” rồi gọi người lớn xem.', feedback: 'Không cầm dao trước. Đợi hướng dẫn.' },
        ],
      },
      {
        id: 'khac-sac-l3-s2',
        hazard: 'việc không sắc được giao',
        prompt: 'Người lớn giao: rửa rau đã cắt sẵn và mang đĩa nguội. Có dao trên bàn. Bé Gấu làm gì?',
        safeText: 'Làm đúng việc được giao; không đụng dao; nhờ người lớn cất dao nếu vướng.',
        safeFeedback: 'Giỏi! Giúp việc nhẹ, để dao cho người lớn.',
        unsafeChoices: [
          { text: 'Cắt thêm rau cho “nhiều hơn”.', feedback: 'Không tự cắt thêm. Làm đúng việc được giao.' },
          { text: 'Dùng dao gạt rau vào tô cho nhanh.', feedback: 'Không dùng dao khi chưa được giao. Dùng dụng cụ người lớn cho phép.' },
        ],
      },
      {
        id: 'khac-sac-l3-s3',
        hazard: 'người lớn ra ngoài một lúc',
        prompt: 'Đang cùng cắt (người lớn đứng cạnh), thì điện thoại reo ở phòng khác. Người lớn bảo “chờ nhé” và đi. Bé Gấu làm gì?',
        safeText: 'Đặt dao xuống thớt, ngồi chờ; không cắt tiếp một mình.',
        safeFeedback: 'Tốt! Không cắt khi người lớn không đứng cạnh.',
        unsafeChoices: [
          { text: 'Cắt nốt cho xong để lập công.', feedback: 'Dừng cắt khi người lớn đi. Chờ họ về.' },
          { text: 'Giao dao cho em nhỏ hơn cắt giúp.', feedback: 'Không giao dao cho em. Để dao yên và chờ người lớn.' },
        ],
      },
      {
        id: 'khac-sac-l3-s4',
        hazard: 'bào / dụng cụ sắc khác',
        prompt: 'Bé Gấu thấy dụng cụ bào rau sắc. Bạn bảo “dùng dễ hơn dao”. Người lớn chưa cho phép. Em làm gì?',
        safeText: 'Không dùng bào. Hỏi người lớn được dùng gì và làm cùng họ.',
        safeFeedback: 'Đúng! Dụng cụ sắc chỉ dùng khi người lớn cho phép và kèm.',
        unsafeChoices: [
          { text: 'Thử bào một miếng cho biết.', feedback: 'Không thử khi chưa được phép. Hỏi người lớn.' },
          { text: 'Bào nhanh rồi giấu dụng cụ.', feedback: 'Không dùng lén. Nhờ người lớn hướng dẫn.' },
        ],
      },
      {
        id: 'khac-sac-l3-s5',
        hazard: 'rửa dao giúp',
        prompt: 'Sau bữa ăn, Bé Gấu muốn giúp rửa. Bồn có dao lẫn bát. Em làm gì?',
        safeText: 'Không tự vớt dao. Nhờ người lớn lấy dao ra trước hoặc để họ rửa phần có dao.',
        safeFeedback: 'Hay! Phần có dao để người lớn; Bé Gấu giúp bát đĩa nguội nếu được giao.',
        unsafeChoices: [
          { text: 'Lục trong nước tìm dao để rửa trước.', feedback: 'Không lục tìm dao dưới nước. Gọi người lớn.' },
          { text: 'Cầm dao chùi thật mạnh cho sạch bóng.', feedback: 'Không tự rửa dao. Để người lớn làm phần đó.' },
        ],
      },
    ],
  },
  {
    id: 'khac-sac-l4',
    moduleId: 'khac-sac',
    gradeBand: '3-5',
    title: 'Đồ sắc để sai chỗ',
    objective: 'Thấy dao / kéo dưới sàn hoặc trong túi đồ chơi → không giấu / không thử; báo người lớn.',
    teacherPrompt: 'Thực hành câu: “Con thấy dao/kéo ở …, nhờ cất ạ.”',
    situations: [
      {
        id: 'khac-sac-l4-s1',
        hazard: 'dao dưới sàn',
        prompt: 'Bé Gấu thấy một con dao nhỏ dưới sàn gần ghế. Em làm gì?',
        safeText: 'Không nhặt bằng cách cầm lưỡi. Gọi người lớn đến cất an toàn.',
        safeFeedback: 'Giỏi! Báo người lớn cất, không tự thử cầm.',
        unsafeChoices: [
          { text: 'Nhặt dao giấu dưới gối cho “an toàn”.', feedback: 'Không giấu dao. Gọi người lớn cất đúng chỗ.' },
          { text: 'Đá dao vào gầm tủ cho khuất mắt.', feedback: 'Không đá hay giấu. Báo người lớn ngay.' },
        ],
      },
      {
        id: 'khac-sac-l4-s2',
        hazard: 'kéo trong hộp đồ chơi',
        prompt: 'Trong hộp đồ chơi có một cây kéo văn phòng. Bé Gấu đang dọn đồ chơi. Em làm gì?',
        safeText: 'Không chơi bằng kéo; gọi người lớn lấy ra và cất.',
        safeFeedback: 'Đúng! Kéo không thuộc hộp đồ chơi — nhờ người lớn cất, không tự lấy.',
        unsafeChoices: [
          { text: 'Cắt tóc gấu bông bằng kéo đó.', feedback: 'Không chơi với kéo. Báo người lớn.' },
          { text: 'Để nguyên trong hộp vì “tiện lần sau”.', feedback: 'Không để kéo trong đồ chơi. Nhờ người lớn cất.' },
        ],
      },
      {
        id: 'khac-sac-l4-s3',
        hazard: 'dao trong túi picnic',
        prompt: 'Khi mở túi picnic, Bé Gấu thấy dao gấp. Người lớn đang xếp thảm. Em làm gì?',
        safeText: 'Không mở lưỡi dao. Nói với người lớn: “Có dao trong túi.”',
        safeFeedback: 'Tốt! Báo rõ để người lớn giữ dao.',
        unsafeChoices: [
          { text: 'Bấm thử lưỡi dao xem có sắc không.', feedback: 'Không bấm thử. Báo người lớn ngay.' },
          { text: 'Cho bạn mượn dao gấp chơi “cắm trại”.', feedback: 'Không cho mượn dao chơi. Đưa người lớn.' },
        ],
      },
      {
        id: 'khac-sac-l4-s4',
        hazard: 'kéo trên ghế sofa',
        prompt: 'Kéo để trên ghế sofa, em nhỏ đang bò tới gần. Bé Gấu làm gì?',
        safeText: 'Nhắc em dừng lại nếu cần, gọi người lớn cất kéo ngay.',
        safeFeedback: 'Hay! Bảo vệ em nhỏ bằng cách báo người lớn, không tự múa kéo.',
        unsafeChoices: [
          { text: 'Cầm kéo vung lên cao cho em khỏi với.', feedback: 'Không vung kéo. Gọi người lớn cất.' },
          { text: 'Nhét kéo xuống khe ghế cho khuất.', feedback: 'Không giấu trong khe ghế. Báo người lớn.' },
        ],
      },
      {
        id: 'khac-sac-l4-s5',
        hazard: 'bạn giấu dao “cho vui”',
        prompt: 'Bạn lấy dao khỏi khay, giấu sau rèm, bảo Bé Gấu đừng nói. Em làm gì?',
        safeText: 'Không giữ bí mật. Nhắc trả dao, cùng báo người lớn cất lại.',
        safeFeedback: 'Đúng! Đồ sắc không giấu chơi — báo người lớn.',
        unsafeChoices: [
          { text: 'Giữ bí mật vì là bạn thân.', feedback: 'An toàn quan trọng hơn bí mật. Báo người lớn.' },
          { text: 'Tìm chỗ giấu khác “khó hơn”.', feedback: 'Không giấu dao. Trả và gọi người lớn.' },
        ],
      },
    ],
  },
  {
    id: 'khac-sac-l5',
    moduleId: 'khac-sac',
    gradeBand: '3-5',
    title: 'Không đùa với vật sắc',
    objective: 'Từ chối trò đùa cầm dao / kéo; chọn cách chơi khác; nhắc bạn tìm người lớn.',
    teacherPrompt: 'Luyện từ chối ngắn và đề xuất trò khác. Không kể chi tiết thương tích.',
    situations: [
      {
        id: 'khac-sac-l5-s1',
        hazard: 'trò đùa “kiếm” bằng dao',
        prompt: 'Bạn đề nghị lấy dao nhà bếp làm “kiếm” chơi. Bé Gấu làm gì?',
        safeText: 'Từ chối, đề nghị trò khác không dùng đồ sắc, báo người lớn nếu bạn vẫn lấy dao.',
        safeFeedback: 'Giỏi! Không đùa bằng dao — chọn trò khác hoặc báo người lớn.',
        unsafeChoices: [
          { text: 'Đồng ý nhưng “đánh nhẹ thôi”.', feedback: 'Không đùa bằng dao dù nhẹ. Từ chối và báo người lớn.' },
          { text: 'Lấy kéo ra làm “kiếm thứ hai”.', feedback: 'Không thêm đồ sắc vào trò. Gọi người lớn.' },
        ],
      },
      {
        id: 'khac-sac-l5-s2',
        hazard: 'thách cắt giấy trên tay',
        prompt: 'Bạn thách cắt tờ giấy đặt trên mu bàn tay bằng kéo. Bé Gấu làm gì?',
        safeText: 'Nói không, nhắc dừng, tìm người lớn nếu bạn sắp làm.',
        safeFeedback: 'Đúng! Không tham gia trò nguy hiểm với kéo.',
        unsafeChoices: [
          { text: 'Làm thử vì giấy mỏng.', feedback: 'Không thử. Dừng và gọi người lớn.' },
          { text: 'Cầm tay bạn để “giữ chặt giấy” giúp.', feedback: 'Không hỗ trợ trò đó. Nhắc dừng và báo người lớn.' },
        ],
      },
      {
        id: 'khac-sac-l5-s3',
        hazard: 'đùa đưa kéo cho nhau',
        prompt: 'Nhóm bạn đưa kéo bằng cách chuyền lưỡi hướng về người nhận. Bé Gấu được chuyền tới. Em làm gì?',
        safeText: 'Không nhận kiểu đó; nhắc đặt kéo xuống bàn, nhờ người lớn chỉ cách đưa kéo an toàn hoặc tạm dừng.',
        safeFeedback: 'Tốt! Đưa kéo đúng cách hoặc để người lớn hướng dẫn — không đùa chuyền.',
        unsafeChoices: [
          { text: 'Chuyền tiếp cho vui.', feedback: 'Không chuyền đùa. Đặt kéo xuống và báo người lớn.' },
          { text: 'Giơ kéo lên cao rồi mới đưa.', feedback: 'Không giơ kéo đùa. Để xuống bàn.' },
        ],
      },
      {
        id: 'khac-sac-l5-s4',
        hazard: 'clip mạng làm đồ sắc',
        prompt: 'Bạn muốn làm theo clip: tự mài que thành “dao” để chơi. Bé Gấu làm gì?',
        safeText: 'Khuyên không làm; chọn trò khác; nếu bạn vẫn tìm dụng cụ sắc thì gọi người lớn.',
        safeFeedback: 'Hay! Không làm theo clip nguy hiểm — nhờ người lớn nếu cần.',
        unsafeChoices: [
          { text: 'Tìm đá giúp bạn mài que.', feedback: 'Không giúp làm vật sắc. Nhắc dừng và báo người lớn.' },
          { text: 'Mang dao thật ra so với que.', feedback: 'Không mang dao thật ra so. Gọi người lớn.' },
        ],
      },
      {
        id: 'khac-sac-l5-s5',
        hazard: 'bạn giận và cầm kéo',
        prompt: 'Bạn đang giận, cầm kéo chỉ lung tung trong phòng. Bé Gấu làm gì?',
        safeText: 'Lùi ra chỗ an toàn, không tranh giành kéo, gọi người lớn ngay.',
        safeFeedback: 'Đúng! Không giằng co — gọi người lớn giúp.',
        unsafeChoices: [
          { text: 'Giật kéo khỏi tay bạn.', feedback: 'Không giật kéo. Gọi người lớn xử lý.' },
          { text: 'Cũng cầm một vật sắc để “cân bằng”.', feedback: 'Không cầm thêm đồ sắc. Lùi ra và báo người lớn.' },
        ],
      },
    ],
  },
];
